export const SAMPLE_DOCTORS = [
  {
    id: 1,
    name: 'Dr. John Smith',
    specialty: 'Cardiology',
    rating: 4.5,
    availability: true,
    location: 'New York',
  },
  {
    id: 2,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 3,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 4,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 5,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 6,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 7,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 8,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 9,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 10,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 11,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 12,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 13,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 14,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 15,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 16,
    name: 'Dr. Raroh Yohnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 17,
    name: 'Dr. John Smith',
    specialty: 'Cardiology',
    rating: 4.5,
    availability: true,
    location: 'New York',
  },
  {
    id: 18,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 19,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 20,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 21,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 22,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 23,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 24,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 25,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  {
    id: 26,
    name: 'Dr. Sarah Johnson',
    specialty: 'Pediatrics',
    rating: 5,
    availability: false,
    location: 'Los Angeles',
  },
  // Add more sample doctors as needed
]
